[package]
name = "double_crypt"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
aes-gcm-siv = "0.11"
chacha20poly1305 = "0.10"
rand = "0.8"
zeroize = "1.5"
anyhow = "1.0"

